# Description: This file is used to define the services that will be used in the development of the RESTful API with Flask.
version: '3.1'

# Define the services that will be used in the development of the RESTful API with Flask.
services:

# Define the MySQL service that will be used in the development of the RESTful API with Flask.
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
  flask_app:
    build:
      context: .
      dockerfile: restfulapi_flask.dockerfile
    volumes:
    - ./app:/app
    ports:
      - "5000:5000"
      - "8888:8888"
    depends_on:
      - mysql
